version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - ikeay
  labels:
  - dependencies
  ignore:
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
